server:
  port: 8080

### Management properties ###

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /_admin
      exposure:
        include: ["info", "health", "loggers", "metrics", "prometheus", "caches", "purge", "refresh"]
  info:
    git:
      mode: full

health:
  config:
    time-to-live: 43200000


spring:
  mondiapayng.datasource:
    jdbc-url: jdbc:mysql://m1.mysql-db91-hh.dev.arvm.de:3306/MondiaPayNG
    username: udWAAR1XX2cd046C
    password: '{cipher}4e3d441947fd9af2a943d1b93259de8e3ea3f809c4b0fbd1b5c4e0ce658cb332b409187afeab0f5ca373c4aa2e581b7c'
    driver-class-name: com.mysql.jdbc.Driver
    pool-name: MerchantOP
    connection-timeout: 30000
    connection-test-query: SELECT 1
    maximum-pool-size: 1
    minimum-idle: 1
    idle-timeout: 600000
    validation-timeout: 5000
  cache:
    cache-names: affiliatesCache
    type: ehcache
    echache.config: classpath:echache.xml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

application:
  subscriptionService:
    url: http://subscriptionadm.stg.arvm.de/v5/api/admin/subscription
  #Affiliates API URL
affiliatesAPI:
  URL: http://mmc-service101.stg.arvm.de:8002/v0/api/affiliate

placebo:
  baseUrl: https://staging-p.mondiamedia.com/api/fetch/image/proxy/0x0/
  sharedSercret: 3daadb9658072b12216bc754874d5baf931d1567
